hwc: gpu_tonemapper: fix checkGlError() & checkEglError()
 * checkGlError():
Remove ´return´ from the end of the loop.

 * checkEglError():
Because eglGetError() returns only the error of the last called EGL
function (compared to glGetError() that may contain values for multiple
recorded errors), it is not necessary to do it in a loop.
This loop was broken in anycase, as it has a ´return´ in the end of
the loop and because it would only loop for a seemingly random number
of 5 times.
Due to the removed ´return´ & for-loop, there is no behavioural change.

Fixes clang warning:
error: loop will run at most once (loop increment never executed)
  [-Werror,-Wunreachable-code-loop-increment]

Test: make libgpu_tonemapper
Signed-off-by: Timi Rautamäki <timi.rautamaki@gmail.com>
Change-Id: I579234940085433bf51623629eed6584d3ee9fe1